import React from "react";

class Start_img3 extends React.Component {
  render() {
    return (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="270"
        height="2000"
        fill="none"
        viewBox="0 0 270 2000"
      >
        <rect
          width="270"
          height="287"
          y="30"
          fill="#C4DFDB"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="270"
          height="256"
          y="345"
          fill="#A7C5EB"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="270"
          height="256"
          y="630"
          fill="#617998"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="270"
          height="256"
          y="915"
          fill="#699CAC"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="270"
          height="100"
          y="1200"
          fill="#CBD9E2"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="270"
          height="187"
          y="1329"
          fill="#C4DFDB"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="270"
          height="256"
          y="1545"
          fill="#A7C5EB"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="270"
          height="256"
          y="1830"
          fill="#617998"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="270"
          height="256"
          y="2115"
          fill="#699CAC"
          opacity="0.4"
          rx="12"
        ></rect>
      </svg>
    );
  }
}

export default Start_img3;
