import React from "react";

class StartImg extends React.Component {
  render() {
    return (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="958"
        height="1080"
        fill="none"
        viewBox="0 0 958 1080"
      >
        <rect
          width="300"
          height="100"
          y="-28"
          fill="#CBD9E2"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="300"
          height="263"
          x="329"
          y="-28"
          fill="#C4DFDB"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="300"
          height="190"
          x="658"
          y="-28"
          fill="#699CAC"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="300"
          height="190"
          x="658"
          y="191"
          fill="#A7C5EB"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="300"
          height="355"
          x="658"
          y="410"
          fill="#C4DFDB"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="300"
          height="212"
          x="329"
          y="264"
          fill="#CBD9E2"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="300"
          height="184"
          x="329"
          y="505"
          fill="#699CAC"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="300"
          height="187"
          y="101"
          fill="#C4DFDB"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="300"
          height="100"
          y="-28"
          fill="#CBD9E2"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="300"
          height="263"
          x="329"
          y="-28"
          fill="#C4DFDB"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="300"
          height="190"
          x="658"
          y="-28"
          fill="#699CAC"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="300"
          height="263"
          x="329"
          y="-28"
          fill="#C4DFDB"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="300"
          height="190"
          x="658"
          y="-28"
          fill="#699CAC"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="300"
          height="187"
          y="101"
          fill="#C4DFDB"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="300"
          height="256"
          y="317"
          fill="#A7C5EB"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="300"
          height="256"
          y="602"
          fill="#617998"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="300"
          height="256"
          y="887"
          fill="#699CAC"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="300"
          height="256"
          x="329"
          y="718"
          fill="#A7C5EB"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="300"
          height="212"
          x="658"
          y="794"
          fill="#CBD9E2"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="300"
          height="256"
          x="329"
          y="1003"
          fill="#617998"
          opacity="0.4"
          rx="12"
        ></rect>
        <rect
          width="300"
          height="212"
          x="658"
          y="1037"
          fill="#C4DFDB"
          opacity="0.4"
          rx="12"
        ></rect>
      </svg>
    );
  }
}

export default StartImg;
